export const API_INVOCATION = "API_INVOCATION";

//authentication related actions
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const GET_TOKEN_VALIDATION = "GET_TOKEN_VALIDATION";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_ERROR = "GET_TOKEN_ERROR";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const UPDATE_NAME = "UPDATE_NAME";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";

//User Details management
export const GET_ALL_USERS_DETAILS = "GET_ALL_USERS_DETAILS";
export const GET_ALL_USERS_DETAILS_SUCCESS = "GET_ALL_USERS_DETAILS_SUCCESS";
export const GET_ALL_USERS_DETAILS_ERROR = "GET_ALL_USERS_DETAILS_ERROR";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_ERROR = "GET_USER_DETAILS_ERROR";
export const GET_USER_ADDRESS = "GET_USER_ADDRESS";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS";
export const GET_USER_ADDRESS_ERROR = "GET_USER_ADDRESS_ERROR";
export const GET_USER_PURCHASE_INFORMATION = "GET_USER_PURCHASE_INFORMATION";
export const GET_USER_PURCHASE_INFORMATION_SUCCESS = "GET_USER_PURCHASE_INFORMATION_SUCCESS";
export const GET_USER_PURCHASE_INFORMATION_ERROR = "GET_USER_PURCHASE_INFORMATION_ERROR";
export const GET_USER_REVIEW_HISTORY = "GET_USER_REVIEW_HISTORY";
export const GET_USER_REVIEW_HISTORY_SUCCESS = "GET_USER_REVIEW_HISTORY_SUCCESS";
export const GET_USER_REVIEW_HISTORY_ERROR = "GET_USER_REVIEW_HISTORY_ERROR";
export const DEACTIVATE_ACCOUNT = "DEACTIVATE_ACCOUNT";
export const DEACTIVATE_ACCOUNT_SUCCESS = "DEACTIVATE_ACCOUNT_SUCCESS";
export const DEACTIVATE_ACCOUNT_ERROR = "DEACTIVATE_ACCOUNT_ERROR";
export const ACTIVATE_ACCOUNT = "ACTIVATE_ACCOUNT";
export const ACTIVATE_ACCOUNT_SUCCESS = "ACTIVATE_ACCOUNT_SUCCESS";
export const ACTIVATE_ACCOUNT_ERROR = "ACTIVATE_ACCOUNT_ERROR";

//faq related actions
export const FAQ_LIST = "FAQ_LIST";
export const SELECTED_FAQ = "SELECTED_FAQ";
export const SELECTED_SECTION = "SELECTED_SECTION";

//inquiry details
export const GET_ALL_INQUIRY_DETAILS = "GET_ALL_INQUIRY_DETAILS";
export const GET_ALL_INQUIRY_DETAILS_SUCCESS = "GET_ALL_INQUIRY_DETAILS_SUCCESS";
export const GET_ALL_INQUIRY_DETAILS_ERROR = "GET_ALL_INQUIRY_DETAILS_ERROR";
export const GET_INQUIRY_DETAILS = "GET_INQUIRY_DETAILS";
export const GET_INQUIRY_DETAILS_SUCCESS = "GET_INQUIRY_DETAILS_SUCCESS";
export const GET_INQUIRY_DETAILS_ERROR = "GET_INQUIRY_DETAILS_ERROR";
export const UPDATE_INQUIRY = "UPDATE_INQUIRY";
export const UPDATE_INQUIRY_DETAILS = "UPDATE_INQUIRY_DETAILS";
export const UPDATE_INQUIRY_SUCCESS = "UPDATE_INQUIRY_SUCCESS";
export const UPDATE_INQUIRY_ERROR = "UPDATE_INQUIRY_ERROR";
export const DELETE_INQUIRY = "DELETE_INQUIRY";
export const DELETE_INQUIRY_SUCCESS = "DELETE_INQUIRY_SUCCESS";
export const DELETE_INQUIRY_ERROR = "DELETE_INQUIRY_ERROR";
export const GET_EXCEL_DATA = "GET_EXCEL_DATA";
export const GET_INQUIRY_DOWNLOAD = "GET_INQUIRY_DOWNLOAD";

//dashboard details
export const GET_DASHBOARD_DETAILS = "GET_DASHBOARD_DETAILS";
export const GET_DASHBOARD_DETAILS_SUCCESS = "GET_DASHBOARD_DETAILS_SUCCESS";
export const GET_DASHBOARD_DETAILS_ERROR = "GET_DASHBOARD_DETAILS_ERROR";
export const GET_DASHBOARD = "GET_DASHBOARD";
export const GET_PIECHART_DETAILS = "GET_PIECHART_DETAILS";
export const GET_PIECHART_DETAILS_SUCCESS = "GET_PIECHART_DETAILS_SUCCESS";
export const GET_PIECHART_DETAILS_ERROR = "GET_PIECHART_DETAILS_ERROR";
export const GET_WEEKLY_REVENUE_DETAILS = "GET_WEEKLY_REVENUE_DETAILS";
export const GET_WEEKLY_REVENUE_DETAILS_SUCCESS = "GET_WEEKLY_REVENUE_DETAILS_SUCCESS";
export const GET_WEEKLY_REVENUE_DETAILS_ERROR = "GET_WEEKLY_REVENUE_DETAILS_ERROR";
export const GET_WEEKLY_PRODUCTS_SELL = "GET_WEEKLY_PRODUCTS_SELL";
export const GET_WEEKLY_PRODUCTS_SELL_SUCCESS = "GET_WEEKLY_PRODUCTS_SELL_SUCCESS";
export const GET_WEEKLY_PRODUCTS_SELL_ERROR = "GET_WEEKLY_PRODUCTS_SELL_ERROR";
export const LAST_SIX_MONTH_REVENUE = "LAST_SIX_MONTH_REVENUE";
export const LAST_SIX_MONTH_REVENUE_SUCCESS = "LAST_SIX_MONTH_REVENUE_SUCCESS";
export const LAST_SIX_MONTH_REVENUE_ERROR = "LAST_SIX_MONTH_REVENUE_ERROR";

//Farm
export const GET_FARM = "GET_FARM";
export const GET_FARM_SUCCESS = "GET_FARM";
export const GET_FARM_ERROR = "GET_FARM";
export const DELETE_FARM = "DELETE_FARM";
export const GET_FARM_NAME = "GET_FARM_NAME";
export const ADD_FARM = "ADD_FARM";
export const UPDATE_FARM = "UPDATE_FARM";
export const GET_FARM_DOWNLOAD = "GET_FARM_DOWNLOAD";
export const SUBMIT_EMAIL = "SUBMIT_EMAIL";

//Device
export const GET_DEVICE = "GET_DEVICE";
export const UPDATE_DEVICE = "UPDATE_DEVICE";
export const GET_DEVICE_DOWNLOAD = "GET_DEVICE_DOWNLOAD";
export const GET_DEVICE_ACTIVITY = "GET_DEVICE_ACTIVITY";

// Camera
export const GET_CAMERA = "GET_CAMERA";
export const UPDATE_CAMERA = "UPDATE_CAMERA";
export const GET_CAMERA_DOWNLOAD = "GET_CAMERA_DOWNLOAD";
export const GET_CAMERA_ACTIVITY = "GET_CAMERA_ACTIVITY";

// User
export const GET_USER = "GET_USER";
export const GET_USER_DOWNLOAD = "GET_USER_DOWNLOAD";
export const UPDATE_USER = "UPDATE_USER";

// News
export const GET_NEWS = "GET_NEWS";
export const DELETE_NEWS = "DELETE_NEWS";
export const ADD_NEWS = "Add_NEWS";
export const UPDATE_NEWS = "UPDATE_NEWS";
export const GET_NEWS_DOWNLOAD = "GET_NEWS_DOWNLOAD";

// FAQS
export const GET_ALL_SECTION = "GET_ALL_SECTION";
export const ADD_SECTION = "ADD_SECTION";
export const DELETE_SECTIONS = "DELETE_SECTIONS";
export const CREATE_SECTIONS = "CREATE_SECTIONS";
export const UPDATE_SECTIONS = "UPDATE_SECTIONS";
export const GET_ALL_SECTION_SUCCESS = "GET_ALL_SECTION_SUCCESS";
export const GET_ALL_SECTION_ERROR = "GET_ALL_SECTION_ERROR";
export const GET_ALL_FAQS_SUCCESS = "GET_ALL_FAQS_SUCCESS";
export const CREATE_FAQ = "CREATE_FAQ";
export const GET_ALL_FAQ = "GET_ALL_FAQ";
export const UPDATE_FAQ = "UPDATE_FAQ";
export const DELETE_FAQ = "DELETE_FAQ";
export const GET_ALL_FAQS = "GET_ALL_FAQS";
export const GET_ALL_FAQS_ERROR = "GET_ALL_FAQS_ERROR";
export const CREATE_FAQS = "CREATE_FAQS";
export const CREATE_FAQS_SUCCESS = "CREATE_FAQS_SUCCESS";
export const CREATE_FAQS_ERROR = "CREATE_FAQS_ERROR";
export const UPDATE_FAQS = "UPDATE_FAQS";
export const UPDATE_FAQS_SUCCESS = "UPDATE_FAQS_SUCCESS";
export const UPDATE_FAQS_ERROR = "UPDATE_FAQS_ERROR";
export const DELETE_FAQS = "DELETE_FAQS";
export const DELETE_FAQS_SUCCESS = "DELETE_FAQS_SUCCESS";
export const DELETE_FAQS_ERROR = "DELETE_FAQS_ERROR";
export const GET_FAQS_BY_ID = "GET_FAQS_BY_ID";
export const GET_FAQS_BY_ID_SUCCESS = "GET_FAQS_BY_ID_SUCCESS";
export const GET_FAQS_BY_ID_ERROR = "GET_FAQS_BY_ID_ERROR";
export const GET_SECTIONS_BY_ID_ERROR = "GET_SECTIONS_BY_ID_ERROR";
export const CREATE_SECTIONS_SUCCESS = "CREATE_SECTIONS_SUCCESS";
export const CREATE_SECTIONS_ERROR = "CREATE_SECTIONS_ERROR";
export const UPDATE_SECTIONS_SUCCESS = "UPDATE_SECTIONS_SUCCESS";
export const UPDATE_SECTIONS_ERROR = "UPDATE_SECTIONS_ERROR";
export const DELETE_SECTIONS_SUCCESS = "DELETE_SECTIONS_SUCCESS";
export const DELETE_SECTIONS_ERROR = "DELETE_SECTIONS_ERROR";
export const GET_SECTIONS_BY_ID = "GET_SECTIONS_BY_ID";
export const GET_SECTIONS_BY_ID_SUCCESS = "GET_SECTIONS_BY_ID_SUCCESS";
